#pragma once
#include <3ds.h>
#include <citro3d.h>

#define RECTANGLETEX 1
#define DIALOGBOXTEX 2
#define DBOXTEX_ICONBOX 3
#define DBOXTEX_BUTTON 4
#define DBOXTEX_BUTTONBACK 5
#define TWLOADERLOGOTEX 6
#define SETTINGSLOGOTEX 7 
#define SETTINGSLOGOTWLTEX 8 
#define SETTINGSLOGOLOADERTEX 9 
#define SETTINGSLOGODEMOTEX 10 
#define SLOT1BOXARTTEX 11 
#define BNRICONTEXNUM 12 
#define BNRICONTEXLAUNCH 13 
#define BOXARTTEXNUM 14 
#define BNRICONTEX[21] 15 
#define BOXARTTEX[6] 16 
#define BOXFULLTEX 17 
#define SHOULDERLTEX 18 
#define SHOULDERRTEX 19 
#define VOLTEX[6] 20 
#define BATTERYICON 21 
#define BATTERYCHRGTEX 22 
#define BATTERYTEX 23 
#define CARTNULLTEX 24 
#define CARTNTRTEX 25 
#define CARTTWLTEX 26
#define CARTCTRTEX 27


#define BLACK	RGBA8(0, 0, 0, 255)
#define GRAY	RGBA8(127, 127, 127, 255)