#ifndef BANNERANDBOXART_H
#define BANNERANDBOXART_H

sf2d_texture *bnricontex1;
sf2d_texture *bnricontex2;
sf2d_texture *bnricontex3;
sf2d_texture *bnricontex4;
sf2d_texture *bnricontex5;
sf2d_texture *bnricontex6;
sf2d_texture *bnricontex7;
sf2d_texture *bnricontex8;
sf2d_texture *bnricontex9;
sf2d_texture *bnricontex10;
sf2d_texture *bnricontex11;
sf2d_texture *bnricontex12;
sf2d_texture *bnricontex13;
sf2d_texture *bnricontex14;
sf2d_texture *bnricontex15;
sf2d_texture *bnricontex16;
sf2d_texture *bnricontex17;
sf2d_texture *bnricontex18;
sf2d_texture *bnricontex19;
sf2d_texture *bnricontex20;
sf2d_texture *bnricontex21;
sf2d_texture *bnricontex22;
sf2d_texture *bnricontex23;
sf2d_texture *bnricontex24;
sf2d_texture *bnricontex25;
sf2d_texture *bnricontex26;
sf2d_texture *bnricontex27;
sf2d_texture *bnricontex28;
sf2d_texture *bnricontex29;
sf2d_texture *bnricontex30;
sf2d_texture *bnricontex31;
sf2d_texture *bnricontex32;
sf2d_texture *bnricontex33;
sf2d_texture *bnricontex34;
sf2d_texture *bnricontex35;
sf2d_texture *bnricontex36;
sf2d_texture *bnricontex37;
sf2d_texture *bnricontex38;
sf2d_texture *bnricontex39;
sf2d_texture *bnricontex40;
sf2d_texture *bnricontex41;
sf2d_texture *bnricontex42;
sf2d_texture *bnricontex43;
sf2d_texture *bnricontex44;
sf2d_texture *bnricontex45;
sf2d_texture *bnricontex46;
sf2d_texture *bnricontex47;
sf2d_texture *bnricontex48;
sf2d_texture *bnricontex49;
sf2d_texture *bnricontex50;

const char* boxartpath1;
const char* boxartpath2;
const char* boxartpath3;
const char* boxartpath4;
const char* boxartpath5;
const char* boxartpath6;
const char* boxartpath7;
const char* boxartpath8;
const char* boxartpath9;
const char* boxartpath10;
const char* boxartpath11;
const char* boxartpath12;
const char* boxartpath13;
const char* boxartpath14;
const char* boxartpath15;
const char* boxartpath16;
const char* boxartpath17;
const char* boxartpath18;
const char* boxartpath19;
const char* boxartpath20;
const char* boxartpath21;
const char* boxartpath22;
const char* boxartpath23;
const char* boxartpath24;
const char* boxartpath25;
const char* boxartpath26;
const char* boxartpath27;
const char* boxartpath28;
const char* boxartpath29;
const char* boxartpath30;
const char* boxartpath31;
const char* boxartpath32;
const char* boxartpath33;
const char* boxartpath34;
const char* boxartpath35;
const char* boxartpath36;
const char* boxartpath37;
const char* boxartpath38;
const char* boxartpath39;
const char* boxartpath40;
const char* boxartpath41;
const char* boxartpath42;
const char* boxartpath43;
const char* boxartpath44;
const char* boxartpath45;
const char* boxartpath46;
const char* boxartpath47;
const char* boxartpath48;
const char* boxartpath49;
const char* boxartpath50;

sf2d_texture *boxarttex1;
sf2d_texture *boxarttex2;
sf2d_texture *boxarttex3;
sf2d_texture *boxarttex4;
sf2d_texture *boxarttex5;
sf2d_texture *boxarttex6;
#endif // BANNERANDBOXART_H

