#ifndef BANNERANDBOXART_H
#define BANNERANDBOXART_H

const char* bnriconpath1;
const char* bnriconpath2;
const char* bnriconpath3;
const char* bnriconpath4;
const char* bnriconpath5;
const char* bnriconpath6;
const char* bnriconpath7;
const char* bnriconpath8;
const char* bnriconpath9;
const char* bnriconpath10;
const char* bnriconpath11;
const char* bnriconpath12;
const char* bnriconpath13;
const char* bnriconpath14;
const char* bnriconpath15;
const char* bnriconpath16;
const char* bnriconpath17;
const char* bnriconpath18;
const char* bnriconpath19;
const char* bnriconpath20;
const char* bnriconpath21;
const char* bnriconpath22;
const char* bnriconpath23;
const char* bnriconpath24;
const char* bnriconpath25;
const char* bnriconpath26;
const char* bnriconpath27;
const char* bnriconpath28;
const char* bnriconpath29;
const char* bnriconpath30;
const char* bnriconpath31;
const char* bnriconpath32;
const char* bnriconpath33;
const char* bnriconpath34;
const char* bnriconpath35;
const char* bnriconpath36;
const char* bnriconpath37;
const char* bnriconpath38;
const char* bnriconpath39;
const char* bnriconpath40;
const char* bnriconpath41;
const char* bnriconpath42;
const char* bnriconpath43;
const char* bnriconpath44;
const char* bnriconpath45;
const char* bnriconpath46;
const char* bnriconpath47;
const char* bnriconpath48;
const char* bnriconpath49;
const char* bnriconpath50;
const char* bnriconpath51;
const char* bnriconpath52;
const char* bnriconpath53;
const char* bnriconpath54;
const char* bnriconpath55;
const char* bnriconpath56;
const char* bnriconpath57;
const char* bnriconpath58;
const char* bnriconpath59;
const char* bnriconpath60;
const char* bnriconpath61;
const char* bnriconpath62;
const char* bnriconpath63;
const char* bnriconpath64;
const char* bnriconpath65;
const char* bnriconpath66;
const char* bnriconpath67;
const char* bnriconpath68;
const char* bnriconpath69;
const char* bnriconpath70;
const char* bnriconpath71;
const char* bnriconpath72;
const char* bnriconpath73;
const char* bnriconpath74;
const char* bnriconpath75;
const char* bnriconpath76;
const char* bnriconpath77;
const char* bnriconpath78;
const char* bnriconpath79;
const char* bnriconpath80;
const char* bnriconpath81;
const char* bnriconpath82;
const char* bnriconpath83;
const char* bnriconpath84;
const char* bnriconpath85;
const char* bnriconpath86;
const char* bnriconpath87;
const char* bnriconpath88;
const char* bnriconpath89;
const char* bnriconpath90;
const char* bnriconpath91;
const char* bnriconpath92;
const char* bnriconpath93;
const char* bnriconpath94;
const char* bnriconpath95;
const char* bnriconpath96;
const char* bnriconpath97;
const char* bnriconpath98;
const char* bnriconpath99;
const char* bnriconpath100;

sf2d_texture *bnricontex1;
sf2d_texture *bnricontex2;
sf2d_texture *bnricontex3;
sf2d_texture *bnricontex4;
sf2d_texture *bnricontex5;
sf2d_texture *bnricontex6;
sf2d_texture *bnricontex7;
sf2d_texture *bnricontex8;
sf2d_texture *bnricontex9;
sf2d_texture *bnricontex10;

const char* boxartpath1;
const char* boxartpath2;
const char* boxartpath3;
const char* boxartpath4;
const char* boxartpath5;
const char* boxartpath6;
const char* boxartpath7;
const char* boxartpath8;
const char* boxartpath9;
const char* boxartpath10;
const char* boxartpath11;
const char* boxartpath12;
const char* boxartpath13;
const char* boxartpath14;
const char* boxartpath15;
const char* boxartpath16;
const char* boxartpath17;
const char* boxartpath18;
const char* boxartpath19;
const char* boxartpath20;
const char* boxartpath21;
const char* boxartpath22;
const char* boxartpath23;
const char* boxartpath24;
const char* boxartpath25;
const char* boxartpath26;
const char* boxartpath27;
const char* boxartpath28;
const char* boxartpath29;
const char* boxartpath30;
const char* boxartpath31;
const char* boxartpath32;
const char* boxartpath33;
const char* boxartpath34;
const char* boxartpath35;
const char* boxartpath36;
const char* boxartpath37;
const char* boxartpath38;
const char* boxartpath39;
const char* boxartpath40;
const char* boxartpath41;
const char* boxartpath42;
const char* boxartpath43;
const char* boxartpath44;
const char* boxartpath45;
const char* boxartpath46;
const char* boxartpath47;
const char* boxartpath48;
const char* boxartpath49;
const char* boxartpath50;
const char* boxartpath51;
const char* boxartpath52;
const char* boxartpath53;
const char* boxartpath54;
const char* boxartpath55;
const char* boxartpath56;
const char* boxartpath57;
const char* boxartpath58;
const char* boxartpath59;
const char* boxartpath60;
const char* boxartpath61;
const char* boxartpath62;
const char* boxartpath63;
const char* boxartpath64;
const char* boxartpath65;
const char* boxartpath66;
const char* boxartpath67;
const char* boxartpath68;
const char* boxartpath69;
const char* boxartpath70;
const char* boxartpath71;
const char* boxartpath72;
const char* boxartpath73;
const char* boxartpath74;
const char* boxartpath75;
const char* boxartpath76;
const char* boxartpath77;
const char* boxartpath78;
const char* boxartpath79;
const char* boxartpath80;
const char* boxartpath81;
const char* boxartpath82;
const char* boxartpath83;
const char* boxartpath84;
const char* boxartpath85;
const char* boxartpath86;
const char* boxartpath87;
const char* boxartpath88;
const char* boxartpath89;
const char* boxartpath90;
const char* boxartpath91;
const char* boxartpath92;
const char* boxartpath93;
const char* boxartpath94;
const char* boxartpath95;
const char* boxartpath96;
const char* boxartpath97;
const char* boxartpath98;
const char* boxartpath99;
const char* boxartpath100;

sf2d_texture *boxarttex1;
sf2d_texture *boxarttex2;
sf2d_texture *boxarttex3;
sf2d_texture *boxarttex4;
sf2d_texture *boxarttex5;
sf2d_texture *boxarttex6;
#endif // BANNERANDBOXART_H

